interface imageInfo {
  url: string;
  width: number;
  height: number;
}

interface colorType {
  red: number;
  green: number;
  blue: number;
  alpha: number;
}

interface boderInfo {
  dominatingColor: colorType;
  homogeneity: boolean;
}

export default interface Category {
  id: number;
  orderBy: number;
  hdThumbnailUrl: string;
  thumbnailUrl: string;
  originalImageUrl: string;
  imageUrl: string;
  originalImage: imageInfo;
  thumbnail: imageInfo;
  borderInfo: boderInfo;
  name: string;
  nameTranslated: Record<string, string>;
  url: string;
  autogeneratedSlug: string;
  customSlug: string;
  productCount: number;
  productCountWithoutSubcategories: number;
  enabledProductCount: number;
  description: string;
  descriptionTranslated: Record<string, string>;
  enabled: boolean;
  productIds: number[];
  isSampleCategory: boolean;
  seoTitle: string;
  seoTitleTranslated: Record<string, string>;
  seoDescription: string;
  seoDescriptionTranslated: Record<string, string>;
  alt: Record<string, Record<string, string>>;
}

interface ResultSet {
  total: number;
  count: number;
  offset: number;
  limit: number;
}

export default interface CategoriesResult(ResultSet) {
  items: Category[];
}
